spring:
  application:
    name: jupjup-api

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

management:
  metrics:
    tags:
      application: jupjup-server
  endpoint:
    health:
      show-details: never