spring:
  application:
    name: jupjup-api

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: jupjup-notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.jubjubapi.*"

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

