#github actions용 테스트 설정

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jupjup_test
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: ixiDJ646uYZDZhs7R6FmJGdhfiOVmgecx32Y6rGv7IyDS8OW4g+7flGw1se7hObS
  expiration: 3600000

ticket-server:
  url: http://localhost:8081
  api-key: ${TICKET_SERVER_API_KEY}
