= 줍줍 API 문서
:doctype: book
:toc: left
:toclevels: 2
:sectnums:
:source-highlighter: highlightjs

== 공통 응답 형식

모든 API는 아래 구조로 응답한다.

=== 성공
operation::auth-signin[snippets='http-response,response-fields']

=== 실패
`success`가 `false`이고 `error.code`로 원인을 구분한다.

operation::auth-signup-duplicate-email[snippets='http-response,response-fields']

== 인증

=== 회원가입
operation::auth-signup[snippets='http-request,request-fields,http-response,response-fields']

.발생 가능한 에러
|===
| 상태 | 코드 | 언제

| 409 | DUPLICATE_EMAIL | 이미 사용 중인 이메일
|===

=== 로그인
operation::auth-signin[snippets='http-request,request-fields,http-response,response-fields']

.발생 가능한 에러
|===
| 상태 | 코드 | 언제

| 401 | INVALID_CREDENTIALS | 이메일 또는 비밀번호 불일치
|===

=== 로그아웃
인증 필요. `Authorization: Bearer {accessToken}` 헤더를 보낸다.

operation::auth-logout[snippets='http-request,http-response,response-fields']

== 티켓

모든 티켓 API는 인증된 사용자만 사용할 수 있다.
요청 시 `Authorization: Bearer {accessToken}` 헤더가 필요하다.

=== 티켓 목록 조회


operation::ticket-list[snippets='http-request,query-parameters,http-response,response-fields']


=== 티켓 단건 조회


operation::ticket-detail[snippets='path-parameters,http-request,http-response,response-fields']


=== 티켓 삭제

관리자(`ADMIN`) 권한이 필요하다.

operation::ticket-delete[snippets='path-parameters,http-request,http-response']


== 취소표 알림 구독


모든 취소표 알림 구독 API는 인증된 사용자만 사용할 수 있다.
요청 시 `Authorization: Bearer {accessToken}` 헤더가 필요하다.

=== 구독 생성


operation::performance-watch-create[snippets='http-request,request-fields,http-response,response-fields']


=== 내 구독 목록 조회


operation::performance-watch-list[snippets='http-request,query-parameters,http-response,response-fields']


=== 구독 해제


operation::performance-watch-delete[snippets='path-parameters,http-request,http-response']


== 취소표 감지

=== 취소표 Webhook 수신

operation::ticket-webhook-canceled[snippets='http-request,request-fields,http-response,response-fields']

== 내부 데이터 동기화

=== 프로그램 동기화

티켓 서버의 프로그램 정보를 동기화한다.

operation::program-sync[snippets='http-request,http-response']


=== 회차 및 좌석 동기화

티켓 서버의 공연 회차 및 좌석 정보를 동기화한다.

operation::performance-seat-sync[snippets='http-request,http-response']


=== 티켓 동기화

티켓 서버의 티켓을 동기화한다.

operation::ticket-polling[snippets='http-request,http-response']